### ISSUE TITLE
配置文件示例中的编码偏好顺序

### ISSUE THREAD

**Issue by ky0utarou** [amtoaer/bili-sync#103]
目前示例配置中给出的编码偏好顺序为`['AV1', 'HEV', 'AVC']`，想问下出于什么样的考虑当前兼容性没那么好的AV1被排在最优先？

**Comment by amtoaer** [comment]
倒也没什么特殊考虑，这个项目最开始是用 python 实现的，依赖 [bilibili-api](https://github.com/Nemo2011/bilibili-api) 库获取视频下载链接，这个库[默认就把 av1 放在了最前面](https://github.com/Nemo2011/bilibili-api/blob/48e6350ccd9596dadf65a6443927c9ccfcdfd6c6/bilibili_api/video.py#L2412)。后面用 rust 重写的时候这部分也改用了rust 实现，逻辑大部分是参考这个库写的，所以把默认值也 copy 过来了（出于个人偏好把 hevc 往前提了）。
我是觉得默认值没那么关键，默认值设置成 av1/hevc 有人会觉得兼容性差，默认值设置成 avc 又会有人觉得占用体积多。既然用户运行前都需要手动编辑一下配置文件，有需求的人自然会改。

**Comment by ky0utarou** [comment]
ok
