### ISSUE TITLE
大佬分辨率应该怎么设置

### ISSUE THREAD

**Issue by yl948** [amtoaer/bili-sync#104]
![image](https://github.com/amtoaer/bili-sync/assets/70079656/778e6815-c1fb-4f4c-bf91-542d8932853c)

下载下来分辨率有点低没有1080p好像只有480

**Comment by amtoaer** [comment]
这种情况一般是由于鉴权失败，可以检查下 credential 是否填写正确。
推荐在匿名窗口中登录，将 credential 字段粘贴过来后关掉窗口，这样可以避免 bilibili web 端和 bili-sync 使用相同凭据产生的刷新冲突。

**Comment by yl948** [comment]
大佬意思是粘贴完就把b站窗口关掉然后启动容器吗

ᴀᴍᴛᴏᴀᴇʀ ***@***.***>于2024年5月8日 周三19:10写道：

**Comment by amtoaer** [comment]
是的

**Comment by yl948** [comment]
好的大佬，我在试一下感谢

ᴀᴍᴛᴏᴀᴇʀ ***@***.***>于2024年5月8日 周三19:34写道：

**Comment by yl948** [comment]
大佬我试了一下还是480的分辨率，请问大佬可以在配置文件里面直接设置下载1080p的吗

不知名的遥 ***@***.***>于2024年5月8日 周三19:35写道：

**Comment by yl948** [comment]
匿名窗口是什么意思，我粘贴了好像就一个sessdata一个不同，其他难受都一致

不知名的遥 ***@***.***>于2024年5月9日 周四20:18写道：

**Comment by yl948** [comment]
感谢大佬

**Comment by amtoaer** [comment]
不客气，程序会在配置文件中的可选分辨率范围内选取最高的分辨率，不需要手动选择。
如果下载了 480p 视频一般是凭据失效导致的（因为 b 站不登录的情况下只能看 480p 视频）。
