### ISSUE TITLE
请问能不能提供视频字幕的下载？以及关闭弹幕的下载

### ISSUE THREAD

**Issue by lin0kin** [amtoaer/bili-sync#105]
1、部分视频需要字幕，比如某些纪录片和外网搬运，能否提供一个选项，当字幕可用时，下载字幕呢？

2、不看弹幕，能不能提供一个选项，用于关闭字幕下载？（没有找到相关的示例）

谢谢！

**Comment by amtoaer** [comment]
抱歉最近工作比较忙：

1. 我看了下 [接口文档](https://socialsisteryi.github.io/bilibili-API-collect/#%F0%9F%8D%B4%E7%9B%AE%E5%BD%95)，没有找到获取字幕的接口，暂时没办法实现。
2. 现在没有提供功能开关，后续可以支持，不过我感觉几 kb 的字幕文件应该没有太大影响？（

**Comment by lin0kin** [comment]
> 抱歉最近工作比较忙：
> 
> 1. 我看了下 [接口文档](https://socialsisteryi.github.io/bilibili-API-collect/#%F0%9F%8D%B4%E7%9B%AE%E5%BD%95)，没有找到获取字幕的接口，暂时没办法实现。
> 2. 现在没有提供功能开关，后续可以支持，不过我感觉几 kb 的字幕文件应该没有太大影响？（

感谢回复！项目真的很好！我自己不看弹幕，所以提出的。感谢你的付出

**Comment by x1ao4** [comment]
主要是如果下载了弹幕一般的播放器可能会默认加载字幕，如果不看弹幕播放视频就要手动去关闭字幕，或者手动删除字幕文件。
