### ISSUE TITLE
刮削时间建议可选为视频发布时间

### ISSUE THREAD

**Issue by lianjun007** [amtoaer/bili-sync#106]
希望可以选择刮削时间为加入收藏夹时间还是视频发布时间。
此外还有个疑问，就是类似v1版本的那些命令在v2怎么使用，极空间的nas用docker部署似乎无法使用（没有ssh权限）。
是否可以考虑做个webUI，不需要什么界面，有文本显示数据库里面的信息（譬如哪些视频已经刮削过了），然后几个按钮就可以了。最重要的就是更新弹幕功能，v1里面的那个refresh_subtitle这个命令。有些视频收藏的早没弹幕……

**Comment by lianjun007** [comment]
还有个不算是问题的问题，就是如果我使用CloudDrive2挂载的网盘去作为视频存放地，会出现bug，无法正常合成视频和音频（temp_video和temp_audio），合成后的视频无法播放并且两个临时文件还在。不能解决也没啥。

**Comment by lianjun007** [comment]
> 抱歉最近比较忙没什么时间搞，要等这阵子忙完才有空做这个。
> 
> 1. 比较简单，现在数据库里有存储视频发布时间，等闲下来可以快速做掉。
> 
> 2. v2 版本暂不支持额外命令，以及前端水平有限不太好做 webui，短期应该不太能做。
> 
> 3. 没有使用过挂载盘操作，但你可以尝试登录容器手动执行一下命令看看有无报错，目前程序用来合成音视频的命令如下：https://github.com/amtoaer/bili-sync/blob/main/src/downloader.rs#L35 。

好的，感谢。只用本地盘就可以了，应该是CloudDrive2的问题。期待新版本，现在最大的问题就是视频发布时间的问题，毕竟这个方便排序之类的，其他的都还可以

**Comment by lemonhall** [comment]
可以试试nicegui，很好用，不用写前端
这就是个挂表格的管理类应用
很适合nicegui



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LianJun ***@***.***&gt;
发送时间: 2024年6月3日 21:37
收件人: amtoaer/bili-sync ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [amtoaer/bili-sync] 刮削时间建议可选为视频发布时间 (Issue #106)





  
抱歉最近比较忙没什么时间搞，要等这阵子忙完才有空做这个。
  
 
比较简单，现在数据库里有存储视频发布时间，等闲下来可以快速做掉。
 
 
 
v2 版本暂不支持额外命令，以及前端水平有限不太好做 webui，短期应该不太能做。
 
 
 
没有使用过挂载盘操作，但你可以尝试登录容器手动执行一下命令看看有无报错，目前程序用来合成音视频的命令如下：https://github.com/amtoaer/bili-sync/blob/main/src/downloader.rs#L35 。
 
   
好的，感谢。只用本地盘就可以了，应该是CloudDrive2的问题。期待新版本，现在最大的问题就是视频发布时间的问题，毕竟这个方便排序之类的，其他的都还可以
