### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Tyc-github** [amtoaer/bili-sync#11]
不知可不可以再加一个变量，可以选择下载的视频、弹幕等文件，能够保留原来的名字呢，虽然有生成的nfo文件可以导入emby、jellyfin等可以看到他的详细信息，但在本地目录看起来都是bv号，想找到他都挺麻烦的

**Comment by cuicsi** [comment]
+1

**Comment by shenleg** [comment]
+1，离开emby完全不知道这个文件是啥

**Comment by amtoaer** [comment]
这里的考虑是防止文件重名，所以使用了一个全局唯一的 id。用视频本身的名字大部分情况应该能正常工作，但万一遇到冲突就有点麻烦。
后续可以做一个自定义文件名称模板的配置，让用户手动填模板。但最近工作比较忙，这个优先级不高。目前打算先抽时间做一下分p视频的处理。

**Comment by duckeaty** [comment]
> 这里的考虑是防止文件重名，所以使用了一个全局唯一的 id。用视频本身的名字大部分情况应该能正常工作，但万一遇到冲突就有点麻烦。 后续可以做一个自定义文件名称模板的配置，让用户手动填模板。但最近工作比较忙，这个优先级不高。目前打算先抽时间做一下分p视频的处理。

增加一个目录和文件名命名的设置就好了，可以采用  视频名.(year).[bv号]，这样不会冲突了。
