### ISSUE TITLE
bili-sync-rs账户每天凌晨登录失败

### ISSUE THREAD

**Issue by wesmile8** [amtoaer/bili-sync#111]
**V2版本在每天凌晨会登录个人账户失败**
![image](https://github.com/amtoaer/bili-sync/assets/75376418/93fb825e-1059-4c42-8173-d7d0739fd28f)
**只能重启容器之后才能登录成功**
![image](https://github.com/amtoaer/bili-sync/assets/75376418/e559b167-7945-45e9-9399-f9e2f5c88c2c)

**Comment by amtoaer** [comment]
之前是否发生过账号在全平台全部登出的情况？这种情况下 credential 是强制失效的，程序内部刷新流程无法正确处理，因此会一直提示未登录。
至于重启“登录成功”，只是因为程序在启动后第二天才会检查刷新 credential，所以没有把问题暴露出来而已。**可以参考 #12 中描述的匿名窗口登录操作，将新的凭据粘贴到 bili-sync 里即可解决。**
目前想到的处理办法是在每次执行扫描前都调用一个需要鉴权的常用接口，如果鉴权没有通过直接报错，可以避免发生这样的误解；同时还可以避免 credential 由于各种原因失效，导致只能下载到 480p 视频的非预期行为。

**Comment by amtoaer** [comment]
https://github.com/amtoaer/bili-sync/releases/tag/v2.0.7
新版本会在每次扫描前检查是否已登录，未登录状态会拒绝运行
