### ISSUE TITLE
视频清晰度

### ISSUE THREAD

**Issue by FQFQFQFQ** [amtoaer/bili-sync#12]
抱歉问一下，清晰的能调整吗，我看下载的基本都是些480p的视频

**Comment by amtoaer** [comment]
程序默认会下载支持的最高清晰度，这种情况可能是因为 cookie 失效了。
推荐的方式是先开个 b 站无痕窗口，登录账号后把鉴权信息复制粘贴下来贴到配置文件里，然后把无痕窗口关掉。我的这样运行一个多月了没有问题。

**Comment by FQFQFQFQ** [comment]
重新配置了一下，好了。感谢。

**Comment by HFCK520** [comment]
这个项目太棒了，真想给作者加鸡腿！有一个小问题这下载的视频文件是不是有问题呀？播放bili-sync下载的视频，显卡直接跑满！而我播放用其它软件下载同一个视频，同样的4K显卡都不怎么动，还有bili-sync下载的视频要小很多。

**Comment by amtoaer** [comment]
应该是因为 nas 不支持硬解 av1，相关的 issue：#26
