### ISSUE TITLE
大佬合集怎么下载

### ISSUE THREAD

**Issue by 15823382203** [amtoaer/bili-sync#120]
只有那种分了p1p2的视频合集才能全部下载。有一些合集只保存了一个视频的话下载时没法下载合集里面所有的视频.是我操作问题吗

**Comment by amtoaer** [comment]
p1、p2 这种是视频分页，目前只支持分页视频下载，暂不支持合集下载。
之前有在尝试做：https://github.com/amtoaer/bili-sync/pull/97 。但 sqlite 数据库不支持修改字段类型，让我写迁移写得很恶心，就暂时搁置了。
估计要等我什么时候整理好心情再开工（

**Comment by 15823382203** [comment]
等大佬更新支持

**Comment by amtoaer** [comment]
最新版本已支持
