### ISSUE TITLE
Up主头像的默认装载路径是啥

### ISSUE THREAD

**Issue by DK6002** [amtoaer/bili-sync#121]
问下，Up主头像的默认装载路径是啥？我试了不是/people，头像图片给我保存到/bili-sync-rs路径下了，有哪位老哥告知下，谢谢！

**Comment by amtoaer** [comment]
配置文件中的 upper_path 就是，你可以修改这个路径，也可以调整 docker 的挂载以对应这个路径。只要最终确保 bili-sync-rs 读取到的该路径对应你 emby 存储中的 /meta/people 路径就好。

**Comment by DK6002** [comment]
感谢，我是用JF，映射和配置文件已更改，可以适配识别了，感谢作者！

**Comment by xushier** [comment]
> 配置文件中的 upper_path 就是，你可以修改这个路径，也可以调整 docker 的挂载以对应这个路径。只要最终确保 bili-sync-rs 读取到的该路径对应你 emby 存储中的 /meta/people 路径就好。

大佬你好，有个问题请教一下。
我已经把Up主头像路径设置好了，图片和nfo也下载了，emby内也显示了人物信息，但是图片不显示。Emby的图片和元数据刮削都没开。如下图：

![image](https://github.com/user-attachments/assets/395f365d-d88c-409a-bdd7-ec6bf82368b0)

![image](https://github.com/user-attachments/assets/5b739e21-d287-4ca4-8d42-4cc0a06bdcf8)

只开了本地元数据读取，图片都是关的。
![image](https://github.com/user-attachments/assets/8ce5bba1-eb5d-4db6-bb1c-d7579f1e10e8)

![image](https://github.com/user-attachments/assets/e50d61f0-87a3-417c-b704-c7dd8fd78bfd)

**Comment by qiaqiaxian** [comment]
> > 配置文件中的 upper_path 就是，你可以修改这个路径，也可以调整 docker 的挂载以对应这个路径。只要最终确保 bili-sync-rs 读取到的该路径对应你 emby 存储中的 /meta/people 路径就好。
> 
> 大佬你好，有个问题请教一下。 我已经把Up主头像路径设置好了，图片和nfo也下载了，emby内也显示了人物信息，但是图片不显示。Emby的图片和元数据刮削都没开。如下图：
> 
> ![image](https://private-user-images.githubusercontent.com/31540107/358114040-395f365d-d88c-409a-bdd7-ec6bf82368b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTQwNDAtMzk1ZjM2NWQtZDg4Yy00MDlhLWJkZDctZWM2YmY4MjM2OGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTBmMGE3NjczZDFiNjkyY2M3YWMzNmM4ZWVkN2JmYzljZjUwYjZiZTRhODhjM2UwOGFhOTBiYmZmODdlMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IMMI9nJC41Gutlqa7GkrdRrSJy6gXmYRCKDJbeEkpQ)
> 
> ![image](https://private-user-images.githubusercontent.com/31540107/358114356-5b739e21-d287-4ca4-8d42-4cc0a06bdcf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTQzNTYtNWI3MzllMjEtZDI4Ny00Y2E0LThkNDItNGNjMGEwNmJkY2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmZkNmFlMGQzYWQzNGY5OGQwOGFkNDhiMDQxODkxMmZlY2Y0ZTA2MjAyYjQzYmI0OGExYTE2ZDBiNmU5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aES949P0sr1sLFoJC0QdYrs9VsNpiDK1djUfZVDpwXA)
> 
> 只开了本地元数据读取，图片都是关的。 ![image](https://private-user-images.githubusercontent.com/31540107/358114817-8ce5bba1-eb5d-4db6-bb1c-d7579f1e10e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTQ4MTctOGNlNWJiYTEtZWI1ZC00ZGI2LWJiMWMtZDc1NzlmMWUxMGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YmQ4ZTEwMjAzYmYwNTM0NTJkYWYwYzVkMjhlNzRjODJmMzg1ZWFhMDhiZTQ5NzhlY2QwNDBiMzY0NzczMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WHGzRvr4ATk088NtObZ_wpjp7bKZKUHquftms-ib5WI)
> 
> ![image](https://private-user-images.githubusercontent.com/31540107/358115346-e50d61f0-87a3-417c-b704-c7dd8fd78bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTUzNDYtZTUwZDYxZjAtODdhMy00MTdjLWI3MDQtYzdkZDhmZDc4YmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDA5ZWE4NzYyMjZmNzFiNTNjZmJkYTk3ZjJlZDlmNGI3MjUwMzg4ZjU2OTExZWY2M2EwN2U2YWJiZWRjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-oi0Nu_hm-naUSj0M7_SG-0ZrlEQewMRcOb0XDEXLBc)

请问下兄弟，问题解决了吗？我也出现了这个情况

**Comment by xushier** [comment]
> > > 配置文件中的 upper_path 就是，你可以修改这个路径，也可以调整 docker 的挂载以对应这个路径。只要最终确保 bili-sync-rs 读取到的该路径对应你 emby 存储中的 /meta/people 路径就好。
> > 
> > 
> > 大佬你好，有个问题请教一下。 我已经把Up主头像路径设置好了，图片和nfo也下载了，emby内也显示了人物信息，但是图片不显示。Emby的图片和元数据刮削都没开。如下图：
> > ![image](https://private-user-images.githubusercontent.com/31540107/358114040-395f365d-d88c-409a-bdd7-ec6bf82368b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTQwNDAtMzk1ZjM2NWQtZDg4Yy00MDlhLWJkZDctZWM2YmY4MjM2OGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTBmMGE3NjczZDFiNjkyY2M3YWMzNmM4ZWVkN2JmYzljZjUwYjZiZTRhODhjM2UwOGFhOTBiYmZmODdlMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IMMI9nJC41Gutlqa7GkrdRrSJy6gXmYRCKDJbeEkpQ)
> > ![image](https://private-user-images.githubusercontent.com/31540107/358114356-5b739e21-d287-4ca4-8d42-4cc0a06bdcf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTQzNTYtNWI3MzllMjEtZDI4Ny00Y2E0LThkNDItNGNjMGEwNmJkY2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmZkNmFlMGQzYWQzNGY5OGQwOGFkNDhiMDQxODkxMmZlY2Y0ZTA2MjAyYjQzYmI0OGExYTE2ZDBiNmU5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aES949P0sr1sLFoJC0QdYrs9VsNpiDK1djUfZVDpwXA)
> > 只开了本地元数据读取，图片都是关的。 ![image](https://private-user-images.githubusercontent.com/31540107/358114817-8ce5bba1-eb5d-4db6-bb1c-d7579f1e10e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTQ4MTctOGNlNWJiYTEtZWI1ZC00ZGI2LWJiMWMtZDc1NzlmMWUxMGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YmQ4ZTEwMjAzYmYwNTM0NTJkYWYwYzVkMjhlNzRjODJmMzg1ZWFhMDhiZTQ5NzhlY2QwNDBiMzY0NzczMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WHGzRvr4ATk088NtObZ_wpjp7bKZKUHquftms-ib5WI)
> > ![image](https://private-user-images.githubusercontent.com/31540107/358115346-e50d61f0-87a3-417c-b704-c7dd8fd78bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzM5OTEsIm5iZiI6MTcyNjM3MzY5MSwicGF0aCI6Ii8zMTU0MDEwNy8zNTgxMTUzNDYtZTUwZDYxZjAtODdhMy00MTdjLWI3MDQtYzdkZDhmZDc4YmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDA5ZWE4NzYyMjZmNzFiNTNjZmJkYTk3ZjJlZDlmNGI3MjUwMzg4ZjU2OTExZWY2M2EwN2U2YWJiZWRjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-oi0Nu_hm-naUSj0M7_SG-0ZrlEQewMRcOb0XDEXLBc)
> 
> 请问下兄弟，问题解决了吗？我也出现了这个情况

没有，作者还没有回复

**Comment by qiaqiaxian** [comment]
@xushier 你是装的套件emby还是docker

**Comment by zhengran14** [comment]
> @xushier 你是装的套件emby还是docker

我用的群晖的套件emby，一样的问题。手动点击演职人员的三个点然后「刷新媒体元数据」是可以刷新出来头像图片的，但是我整个媒体库「刷新媒体元数据」头像出不来。路径已经配好了，emby也能够读取路径下的头像（不然手动三个点也刷不出来）
