### ISSUE TITLE
投稿视频属于合集还是列表？

### ISSUE THREAD

**Issue by weigeloveu** [amtoaer/bili-sync#129]
https://space.bilibili.com/452412746/video
大佬你好，请教一下支持投稿视频下载吗？如果支持的话投稿视频属于合集还是列表？

**Comment by amtoaer** [comment]
暂时还不支持，不过上次重构把这种能提供一系列视频的结构抽象出来了，后面支持 up 投稿、稍后再看之类的都比较简单。近两周有时间的话可以做一下。

**Comment by weigeloveu** [comment]
感谢大佬，太牛了
