### ISSUE TITLE
合集能下载为剧集形式么？

### ISSUE THREAD

**Issue by loveu5522** [amtoaer/bili-sync#130]
就是合集下载为连续剧形式的带上下集这样，这样是否会好一些，目前合集下载是为单集文件

**Comment by amtoaer** [comment]
在现在这套框架上不太好实现。

现在整体上是这样设计的：
1. 将视频列表、收藏夹这种能够提供一系列 video 的结构（以下称之为 video list）存储为外层文件夹；
2. 对于 video list 中的每个 video，如果包含多个 page，认为 video 是剧集，每个 page 是单集；
3. 如果只包含一个 page，认为 video 是电影。

在这种抽象下，可以简单地将 video list 对应的文件夹作为“混合内容”添加到媒体服务器中，且同时支持单页和多页视频。

而要实现你想要的效果，意味着剧集不仅要用来表示“包含多个 page 的 video”，还要用来表示“包含多个单 page 的 video 的 video list”。需要将 video list 区分为两类：
1. 提供一系列 video，且每个 video 都包含一个或多个 page 的 video list（收藏夹以及后面可能要添加的 up 主投稿视频）
2. 提供一系列 video，但每个 video 都仅包含一个 page 的 video list（视频合集、视频列表）

对第二类 video list 做单独处理，实现按剧集排布的文件布局才能做到。感觉投入回报比有点低，目前不太考虑做。

**Comment by loveu5522** [comment]
好吧，感觉好复杂，那我还是使用混合内容吧。
