### ISSUE TITLE
Docker新部署的，启动后日志一直显示检测登录状态时遇到错误

### ISSUE THREAD

**Issue by HelloMusician** [amtoaer/bili-sync#136]
<html>
<body>

[2m2024-07-12 14:56:12.299[0m [31mERROR[0m [2mbili_sync_rs[0m[2m:[0m 检查登录状态时遇到错误：error sending request for url (https://api.bilibili.com/x/web-interface/nav/stat)，等待下一轮执行
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by HelloMusician** [comment]
会不会是端口的问题？请问这个应用的端口使用的是哪个？

**Comment by amtoaer** [comment]
程序不暴露 http 端口，应该和端口无关。日志说明 bili-sync 向 b 站 api 发送请求失败，麻烦排查一下 docker 容器是否能够正常访问互联网。

**Comment by HelloMusician** [comment]
> 程序不暴露 http 端口，应该和端口无关。日志说明 bili-sync 向 b 站 API 发送请求失败，麻烦排查一下 docker 容器是否能够正常访问互联网。

我用虚拟机测试环境部署了一下，成功了。测试环境没有开防火墙，正式环境的群辉开了防火墙，是不是这个原因导致的

**Comment by HelloMusician** [comment]
![image](https://github.com/user-attachments/assets/6c9a8000-040c-4acc-bf64-41c7a150cfba)
内网测试的时候，显示账号未登录，这个咋解决，后面一堆日志，但是下载文件夹里没东西
[bilisync.zip](https://github.com/user-attachments/files/16190572/bilisync.zip)

**Comment by amtoaer** [comment]
提示账号未登录说明你填写的凭据是错误的。请参考文档，检查 credential 中填写的项目是否正确。
Permission denied 是权限问题，一般是因为你运行 bili-sync 使用的 user 没有目的文件夹的写入权限。

**Comment by HelloMusician** [comment]
> 提示账号未登录说明你填写的凭据是错误的。请参考文档，检查 credential 中填写的项目是否正确。 Permission denied 是权限问题，一般是因为你运行 bili-sync 使用的 user 没有目的文件夹的写入权限。

谢谢，就是下载文件夹权限问题，已经解决了。
