### ISSUE TITLE
win10下载 bili-sync-rs-Windows-x86_64.zip程序闪退

### ISSUE THREAD

**Issue by xingyaolunhui** [amtoaer/bili-sync#138]
打开exe文件直接闪退，防火墙没开

**Comment by Ricardo-M-Lu0** [comment]
win11也闪退

**Comment by amtoaer** [comment]
请阅读文档的[快速开始](https://bili-sync.allwens.work/quick-start#%E7%A8%8B%E5%BA%8F%E9%85%8D%E7%BD%AE)章节。

**Comment by xingyaolunhui** [comment]
> 请阅读文档的[快速开始](https://bili-sync.allwens.work/quick-start#%E7%A8%8B%E5%BA%8F%E9%85%8D%E7%BD%AE)章节。


不行，配置完参数，双击exe文件还是闪退

**Comment by amtoaer** [comment]
在当前文件夹打开 terminal，输入 `./bili-sync-rs.exe` 执行，应该可以看到错误信息。

**Comment by xingyaolunhui** [comment]
[2m2024-07-23 16:21:41.688[0m [32m INFO[0m [2mbili_sync_rs::config[0m[2m:[0m 配置加载完毕，覆盖刷新原有配置
[2m2024-07-23 16:21:41.690[0m [32m INFO[0m [2mbili_sync_rs::config[0m[2m:[0m 校验配置文件内容...
[2m2024-07-23 16:21:41.690[0m [31mERROR[0m [2mbili_sync_rs::config[0m[2m:[0m Credential 信息不完整，请确保填写完整
thread 'main' panicked at crates\bili_sync\src\config.rs:165:13:
位于 C:\Users\55555555\AppData\Roaming\bili-sync\config.toml 的配置文件不合法，请参考提示信息修复后继续运行
note: run with `RUST_BACKTRACE=1` environment variable to display a backtra

> 在当前文件夹打开 terminal，输入 `./bili-sync-rs.exe` 执行，应该可以看到错误信息。

**Comment by amtoaer** [comment]
“Credential 信息不完整，请确保填写完整”
