### ISSUE TITLE
能添加一个不下载视频，其他保持下载的版本吗

### ISSUE THREAD

**Issue by lucienlmy** [amtoaer/bili-sync#142]
因为大部分时候只是想知道某些不存在的收藏夹视频是什么，并不想下载下来，几千个收藏太占用空间了

**Comment by amtoaer** [comment]
下载视频是这个项目的核心功能，短期没有单独剥离的打算。
而且只想要个视频名字的话，用这个项目有点太重量级了，用 python 引入 [bilibili api](https://github.com/Nemo2011/bilibili-api) 可能二十行代码就能实现（

**Comment by lucienlmy** [comment]
> 下载视频是这个项目的核心功能，短期内没有单独分割的打算。 而且只想要一个视频名字的话，用这个项目有点太重了，用 python 引入[bilibili api](https://github.com/Nemo2011/bilibili-api)可能二十行代码就能实现（

或者你能不能在设置里面加一个选项，开启和关闭视频下载功能

**Comment by lucienlmy** [comment]
> 下载视频是这个项目的核心功能，短期内没有单独分割的打算。 而且只想要一个视频名字的话，用这个项目有点太重了，用 python 引入[bilibili api](https://github.com/Nemo2011/bilibili-api)可能二十行代码就能实现（

你提供的源码是完整的吗，能否编译，我想试试把下载视频的那段代码注释掉，再编译出来试试

**Comment by amtoaer** [comment]
@lucienlmy 是完整的，可以直接在项目目录执行 `cargo build --release` 编译。

**Comment by lucienlmy** [comment]
> @lucienlmy 是完整的，可以直接在项目目录执行 `cargo build --release` 编译。

// pub async fn get_page_analyzer(&self, page: &PageInfo) -> Result<PageAnalyzer> {
//     let mut res = self
//         .client
//         .request(Method::GET, "https://api.bilibili.com/x/player/wbi/playurl")
//         .query(&[
//             ("avid", self.aid.as_str()),
//             ("cid", page.cid.to_string().as_str()),
//             ("qn", "127"),
//             ("otype", "json"),
//             ("fnval", "4048"),
//             ("fourk", "1"),
//         ])
//         .send()
//         .await?
//         .error_for_status()?
//         .json::<serde_json::Value>()
//         .await?
//         .validate()?;
//     Ok(PageAnalyzer::new(res["data"].take()))
// }

这段代码是下载视频的吧，刚试着注释了下，再编译出错了，应该是还有其他的方式依赖get_page_analyzer，你有没有更好的办法

**Comment by amtoaer** [comment]
把其他地方使用的代码注释掉肯定无法编译啊...
简单一点的话，把 `pub async fn fetch_page_video` 的函数体全部删掉，只保留最后面的 `Ok(())` 应该就可以了。

**Comment by lucienlmy** [comment]
可以了，谢谢

**Comment by lucienlmy** [comment]
> 把其他地方使用的代码注释掉肯定无法编译啊... 简单一点的话，把`pub async fn fetch_page_video`函数体全部删掉，只保留最后面的`Ok(())`应该就可以了。

可以了，谢谢
