### ISSUE TITLE
有没有办法选择H264编码格式进行下载

### ISSUE THREAD

**Issue by Nanam1** [amtoaer/bili-sync#26]
现在默认下载最高清晰度的时候，默认AV1编码，Nas核显不支持硬解

**Comment by Shattered217** [comment]
同求，emby网页版有时候会自动转码软解，有一次无意间点进个4k，CPU满载直接给宿主机干崩了😢

**Comment by komaedaXnagito** [comment]
bilibili_api支持选择编码格式的
detector.detect_best_streams(
codecs=[VideoCodecs.HEV]
)

**Comment by oevery** [comment]
其实我觉得 h265 编码格式挺好的，大多数设备都能硬解，能支持 av1解码的设备实在是太少了，h265 占用也小。能自定义配置是最好的。

**Comment by Shattered217** [comment]
> bilibili_api支持选择编码格式的 detector.detect_best_streams（ codecs=[VideoCodecs.HEV] )

请问docker的配置文件应该如何修改

**Comment by komaedaXnagito** [comment]
> > bilibili_api支持选择编码格式的 detector.detect_best_streams（ codecs=[VideoCodecs.HEV] )
> 
> 请问docker的配置文件应该如何修改

作者没支持，自行fork代码修改打镜像，或者等作者更新

**Comment by komaedaXnagito** [comment]
> 其实我觉得 h265 编码格式挺好的，大多数设备都能硬解，能支持 av1解码的设备实在是太少了，h265 占用也小。能自定义配置是最好的。

说的对

**Comment by amtoaer** [comment]
https://github.com/amtoaer/bili-sync/releases/tag/1.1.4
