### ISSUE TITLE
下载失败，报错 接口返回错误代码：-400，信息：请求错误

### ISSUE THREAD

**Issue by KiraHau** [amtoaer/bili-sync#35]
![image](https://github.com/amtoaer/bili-sync/assets/46923871/95edc18e-8374-4760-a400-24a7594e5cd4)

**Comment by amtoaer** [comment]
发现了相同的问题，测试更新上游依赖可解，今晚发个新版本

**Comment by amtoaer** [comment]
@KiraHau 试试这个：https://github.com/amtoaer/bili-sync/releases/tag/1.1.5
