### ISSUE TITLE
关于字幕字体大小的问题

### ISSUE THREAD

**Issue by lemonhall** [amtoaer/bili-sync#37]
刚才忘了说了，用jellyfin在看字幕的时候，发现，不同的分辨率下的字体是不一样的

没认真研究，但猜想是因为视频分辨率不同导致的

所以可以字体的生成需要依赖不同的分辨率去动态调整

可能emby没啥问题，所以说一声，没仔细去看emby，因为那个东西的客户端不开源

**Comment by amtoaer** [comment]
emby 也有相同的问题，但是没有找到比较好的处理方式，可能需要研究一下字幕字号的设置规则
