### ISSUE TITLE
cookies的问题

### ISSUE THREAD

**Issue by lemonhall** [amtoaer/bili-sync#38]
据我观察，会员的cookies会在大约1-2天内过期

之后下载的就都是480p的低清晰度视频了

需要更新一下config文件里的几件套

不太好搞的感觉，估计需要模拟游览器访问bilibili

也不知道b站的机制

**Comment by amtoaer** [comment]
我这里稳定运行很久了，还没有出现过问题。
现在 bili-sync 的行为与[上游研究发现的 web 端刷新机制](https://github.com/SocialSisterYi/bilibili-API-collect/blob/a46f140fde73530868ce9db5f613deed8d5c645e/docs/login/cookie_refresh.md#%E5%88%B7%E6%96%B0%E6%AD%A5%E9%AA%A4%E4%BC%AA%E4%BB%A3%E7%A0%81)保持一致。会在每天第一次执行时检验 cookie 是否需要刷新，如果需要就会触发刷新并把新 cookie 写到配置文件里，所以理论上是不会失效的。
可能的情况是，同一份 cookie 在写入 bili-sync 后没有在网页端清除，导致网页端先行触发了刷新流程，使 bili-sync 持有的原始的 cookie 失效。
解决办法是在一个无痕窗口内授权，授权后将凭据粘贴到 bili-sync 后关掉无痕窗口，让同一份 cookie 仅在一个位置管理，参考：https://github.com/amtoaer/bili-sync/issues/12 。
