### ISSUE TITLE
合集视频只能下载第一P

### ISSUE THREAD

**Issue by soulans** [amtoaer/bili-sync#4]
对于分P的合集视频，无论在哪一P添加收藏，最终会被下载的只有第一P。如果可能希望能支持一下。

**Comment by amtoaer** [comment]
Get，但有一说一我写的时候考虑到了这一点，做了条件判断暂时忽略视频合集，可能是这个判断写的有点问题。 🤣

**Comment by dawnsummit** [comment]
我之前有一个收藏夹自动下载脚本，已经实现了这个。但是我没有写nfo这些文件，所以Emby需要重新识别。顺便问一下，你这个vscode主题好看啊，是什么主题啊？

**Comment by soulans** [comment]
> Get，但有一说一我写的时候考虑到了这一点，做了条件判断暂时忽略视频合集，可能是这个判断写的有点问题。 🤣

谢谢回复！希望以后能增加该功能。因为有些合集也非常棒非常值得下载下来！

（另外确实vscode主题很好看！我也想问！）

**Comment by amtoaer** [comment]
主题是 [doki theme](https://github.com/doki-theme/doki-theme-vscode)，具体来说，颜色主题选的是 Doki Theme: DDLC: Sayori，背景图片选的是 Yuzuriha Inori's Wallpaper。

---

关于分p视频，我看emby是[支持文件堆叠](https://emby.media/support/articles/Movie-Naming.html#split-video-files-file-stacking)的，为分p视频的文件名添加part后缀就行，但这样应该没办法保留分p视频的名称，可能还得再调研一下。

**Comment by duckeaty** [comment]
> 主题是 [doki theme](https://github.com/doki-theme/doki-theme-vscode)，具体来说，颜色主题选的是 Doki Theme: DDLC: Sayori，背景图片选的是 Yuzuriha Inori's Wallpaper。
> 
> 关于分p视频，我看emby是[支持文件堆叠](https://emby.media/support/articles/Movie-Naming.html#split-video-files-file-stacking)的，为分p视频的文件名添加part后缀就行，但这样应该没办法保留分p视频的名称，可能还得再调研一下。

不用part，直接s01exx按电视剧的格式分集更好。建库时选择混合（同时支持电影和电视）

**Comment by itangqiao** [comment]
超级期待分P下载功能！！！搭建这个主要是为了UP搬运的优质课程，太容易被举报下架了😂

**Comment by momozi-coder** [comment]
期待合集下载功能！～

**Comment by lipind** [comment]
希望合集下载可以指定收藏夹开启或关闭，不然只想收藏音乐合集的一首，会把整个合集下载下了，储存爆炸

**Comment by amtoaer** [comment]
可以试试更新 [1.1.7](https://github.com/amtoaer/bili-sync/releases/tag/1.1.7) 版本后打开 `paginated_video` 选项。
