### ISSUE TITLE
新增对极空间影视墙的适配

### ISSUE THREAD

**Issue by Jiaayu** [amtoaer/bili-sync#41]
今天使用了一下发现极空间好像识别不了nfo，查了一下发现极空间只支持电影的nfo，所以只要把文件中的episodedetails改为movie就行了，大佬可以更新一下这个吗![image](https://github.com/amtoaer/bili-sync/assets/53005519/bb87f067-52fb-493a-87e3-682b62e822c4)![image](https://github.com/amtoaer/bili-sync/assets/53005519/71459a80-2f38-4a68-842f-fecbb78f2803)

**Comment by amtoaer** [comment]
是的，这个是 bug，我的 nfo 类型写错了，下个版本会修。

**Comment by amtoaer** [comment]
可以试试 [1.1.7](https://github.com/amtoaer/bili-sync/releases/tag/1.1.7) 版本。
