### ISSUE TITLE
vsc界面主题和代码主题颜色很好看，在哪找的什么名字  能否告知下？谢谢了！

### ISSUE THREAD

**Issue by wa131** [amtoaer/bili-sync#42]
vsc界面主题和代码主题颜色很好看，在哪找的什么名字，能否告知下？谢了！
![image](https://github.com/amtoaer/bili-sync/assets/160009774/873b28f3-fc3d-4aa3-92f7-673f810517d2)

###

**Comment by amtoaer** [comment]
主题是[doki theme](https://marketplace.visualstudio.com/items?itemName=unthrottled.doki-theme)，颜色主题选择 Doki Theme: DDLC: Sayori，然后 ctrl+shift+p 打开菜单，选择 Doki-Theme: Install Yuzuriha Inori's Wallpaper。
