### ISSUE TITLE
如何添加多个收藏夹

### ISSUE THREAD

**Issue by bainw2023** [amtoaer/bili-sync#43]
想问下大佬们，如何添加多个收藏夹，config的配置文件如何填写？

**Comment by 2691432189** [comment]
![屏幕截图 2024-02-21 170037](https://github.com/amtoaer/bili-sync/assets/44900334/d03a58fb-af9d-4a9d-9e67-877b6680a7fa)
这样子

**Comment by bainw2023** [comment]
> ![屏幕截图 2024-02-21 170037](https://private-user-images.githubusercontent.com/44900334/306560884-d03a58fb-af9d-4a9d-9e67-877b6680a7fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDcyNzMsIm5iZiI6MTcwODUwNjk3MywicGF0aCI6Ii80NDkwMDMzNC8zMDY1NjA4ODQtZDAzYTU4ZmItYWY5ZC00YTlkLTllNjctODc3YjY2ODBhN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA5MTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MjI4NTEzMmQ3NDE5ZTE4NWUwNDRiZTY3NzA1NWNiNWJjMDY4M2RlZTVlYzVkMjdjZDlkMDk2ZDY2ZDc5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zNMJe9Spg1fq2VbkAtCEpbYiPTyQwtrWApdbJuEr1_0)这样子

![1708507015946](https://github.com/amtoaer/bili-sync/assets/154728281/ff2b388c-d457-4b02-88f6-02e3a0384cb9)你好，我的报错误。

**Comment by bainw2023** [comment]
> ![屏幕截图 2024-02-21 170037](https://private-user-images.githubusercontent.com/44900334/306560884-d03a58fb-af9d-4a9d-9e67-877b6680a7fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDcyNzMsIm5iZiI6MTcwODUwNjk3MywicGF0aCI6Ii80NDkwMDMzNC8zMDY1NjA4ODQtZDAzYTU4ZmItYWY5ZC00YTlkLTllNjctODc3YjY2ODBhN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA5MTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MjI4NTEzMmQ3NDE5ZTE4NWUwNDRiZTY3NzA1NWNiNWJjMDY4M2RlZTVlYzVkMjdjZDlkMDk2ZDY2ZDc5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zNMJe9Spg1fq2VbkAtCEpbYiPTyQwtrWApdbJuEr1_0)这样子

谢谢大佬，已解决，标点符号错误，逗号用错了
