### ISSUE TITLE
试达到最大次数

### ISSUE THREAD

**Issue by 18ss** [amtoaer/bili-sync#44]
日志显示试达到最大次数是为什么

**Comment by amtoaer** [comment]
麻烦给出带有上下文的异常信息，只看文本不好确认

**Comment by 18ss** [comment]
![斗鱼直播截图_20240224162424](https://github.com/amtoaer/bili-sync/assets/68369198/482c9e96-a485-44e1-9504-cb2f8672df83)

**Comment by amtoaer** [comment]
看起来像是 bilibili api 没有正常返回，麻烦依次确认：
1. 网络正常
2. 凭据设置正确
3. 收藏夹 id 设置正确
4. 凭据对应的账号有该收藏夹的访问权限

**Comment by 18ss** [comment]
那应该是凭证问题。凭据会经常变是为什么，我重新设置后，过几天就变了

**Comment by 18ss** [comment]
ac_time_value我也设置了

**Comment by amtoaer** [comment]
可能是由于同一份凭据在浏览器和 bili-sync 中同时存在，浏览器端触发刷新导致 bili-sync 中的凭据失效了。
建议是在无痕窗口中登录然后把凭据粘过来，这样凭据仅在 bili-sync 维护，不会遇到冲突。我这样挂了几个月没有问题。

**Comment by 18ss** [comment]
![斗鱼直播截图_20240302134401](https://github.com/amtoaer/bili-sync/assets/68369198/27ef8197-b01a-4d28-a0c5-87e74b01647b)

**Comment by 18ss** [comment]
现在出现了这个错误是什么原因

**Comment by amtoaer** [comment]
连接 b 站 api 超时了，可能是你那里网络环境不太好，我把这个异常忽略掉吧
