### ISSUE TITLE
cannot connect to host api 

### ISSUE THREAD

**Issue by hj3013** [amtoaer/bili-sync#48]
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.bilibili.com:443 ssl:default [Try again]
2024-03-08 15:08:01.203 | INFO     | __main__:<module>:53 - Cleaning up resources...
2024-03-08 15:08:01.208 | INFO     | __main__:<module>:55 - Done, exited.

** Press ANY KEY to close this window ** 

前段时间还能运行这段时间，凉凉了。这是啥情况？

**Comment by amtoaer** [comment]
看报错是连接 bilibili api 失败了，可以麻烦排查下网络问题吗？

**Comment by hj3013** [comment]
> 看报错是连接 bilibili api 失败了，可以麻烦排查下网络问题吗？

解决了，不知道网路哪里问题，容器网络类型改成，host，可以了。
