### ISSUE TITLE
【建议】能否让下载的视频以视频原本的名字作为展示呢？

### ISSUE THREAD

**Issue by kaixin1995** [amtoaer/bili-sync#49]
你好，请问能否给下载的视频不要以视频ID的名字展示，而是以它们原本真实的名字作为展示呢？  这样使用外部视频播放的时候也可以根据文件名分辨出谁是谁。

**Comment by LQYHYQ** [comment]
这个我之前也提过，不过我提的是在外面套层文件夹，文件夹用视频标题，然后视频相关文件可以继续用视频ID，同一个视频保存在一个文件夹中，相当于每个视频一个文件夹。这个功能可以自己改源码实现，在保存路径加一层，我自己已经魔改使用了。

**Comment by kaixin1995** [comment]
离开状态，勿回

**Comment by kaixin1995** [comment]
周六有时间看了下代码，已经解决这个问题了。  只需要修改models.py这个文件即可。我把我修改过后的放出来，有需要的可以自取。

**Comment by kaixin1995** [comment]
[models.zip](https://github.com/amtoaer/bili-sync/files/14623860/models.zip)
以上是修改过后的代码

**Comment by kaixin1995** [comment]
> 这个我之前也提过，不过我提的是在外面套层文件夹，文件夹用视频标题，然后视频相关文件可以继续用视频ID，同一个视频保存在一个文件夹中，相当于每个视频一个文件夹。这个功能可以自己改源码实现，在保存路径加一层，我自己已经魔改使用了。

已经实现了。谢了，之前对py的代码不太熟悉。

**Comment by rkongzy** [comment]
你好，发现有个问题，用中文文件名的话，标题中有特殊符号的话emby就无法播放，比如标题里有 | 这个符号，emby就没法播放
