### ISSUE TITLE
能否按自己创建的收藏文件夹 分类存放呢。

### ISSUE THREAD

**Issue by jianzhichu** [amtoaer/bili-sync#50]
能否按自己创建的收藏文件夹 分类存放呢。

**Comment by LQYHYQ** [comment]
> 能否按自己创建的收藏文件夹 分类存放呢。
配置文件这就能配置啊，不同收藏夹不同文件保存位置
![image](https://github.com/amtoaer/bili-sync/assets/38932132/c2553c0c-c39a-4598-8077-d367709bb2d9)

**Comment by xiangjing102** [comment]
> https://api.bilibili.com/x/v3/fav/folder/created/list-all?up_mid=xxx

请教一下这个需要怎么改配置文件呢？

**Comment by xiangjing102** [comment]
> https://api.bilibili.com/x/v3/fav/folder/created/list-all?up_mid=xxx

请教一下这个需要怎么改配置文件呢？

**Comment by amtoaer** [comment]
目前不支持这样配置，你可以手动请求该接口，构造出 收藏夹 id : 想要存储的路径 这样的 json 结构粘贴到配置文件里。
