### ISSUE TITLE
[建议]Windows环境下的支持

### ISSUE THREAD

**Issue by 603185423** [amtoaer/bili-sync#51]
Windows下无法安装uvloop依赖
去除`import uvloop`并修改为`asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())`后能正常启动脚本

能否考虑通过动态导入库的方式, 为Windows环境提供支持?

目前在Windows下, 未开启系统代理时 脚本工作正常

**Comment by amtoaer** [comment]
你好，目前我在尝试用 rust 重写该项目：https://github.com/amtoaer/bili-sync/tree/v2.0，该版本应该没有平台兼容性问题。
目前 Python 版本仍然接受 PR，你可以将你的改动提交为 PR，我会合并到主分支里。

**Comment by amtoaer** [comment]
可以试试： https://github.com/amtoaer/bili-sync/releases/tag/v2.0.0
我先 close 掉了，有问题的话再 reopen。
