### ISSUE TITLE
怎么让emby识别视频作者信息

### ISSUE THREAD

**Issue by chux1995** [amtoaer/bili-sync#56]
<img width="853" alt="image" src="https://github.com/amtoaer/bili-sync/assets/36070604/c254dfce-a2a8-467b-b7ef-73c3fa7699e0">
我这里的文件夹结构，挂载目录
<img width="683" alt="image" src="https://github.com/amtoaer/bili-sync/assets/36070604/b8fcd062-b03d-49e5-8225-e39ff34d310e">

**Comment by chux1995** [comment]
<img width="672" alt="image" src="https://github.com/amtoaer/bili-sync/assets/36070604/837c8f4a-8dcf-4d20-864f-ffb09628623f">

**Comment by chux1995** [comment]
都是最新版本的镜像

**Comment by chux1995** [comment]
<img width="936" alt="image" src="https://github.com/amtoaer/bili-sync/assets/36070604/082b3ac0-8ed0-426c-b5b3-2eb71b47a43d">
怎么设置分 p 的属性，默认是”page_name": "{{bvid}}",我想设置成分 p 的标题，而现在是视频的 id。

**Comment by amtoaer** [comment]
目前首页的 README 是对于 v2.0 的说明，暂未进行 docker 打包。
docker 版是使用 v1.x 版本的源码，请参考 [v1.x](https://github.com/amtoaer/bili-sync/tree/v1.x) 的 README 与 [v1.x 的 release 说明](https://github.com/amtoaer/bili-sync/releases)。
page_name 自定义是 v2.0 引入的功能，1.x 并不支持。
