### ISSUE TITLE
非会员登录后下载的视频清晰度问题。

### ISSUE THREAD

**Issue by shuer001** [amtoaer/bili-sync#60]
你好，感谢开发大大，非常好用。
就是登录后，同视频，用第三方浏览器插件下载的视频是170M，docker部署下载的是94M。 为什么会有这么大的差异呢？是设置问题吗？？
我是按照模版设置的，大小设置没有变动。测试了几个都会大小有明细差异。
如图对比都是1080p，但是码率不同。

![QQ截图20240414124449](https://github.com/amtoaer/bili-sync/assets/48412081/f97d15f6-597c-4591-be48-78feca0c31d4)
![QQ截图20240414124522](https://github.com/amtoaer/bili-sync/assets/48412081/e085c4c4-d6ad-42f4-857f-364b526524bc)
![QQ截图20240414124609](https://github.com/amtoaer/bili-sync/assets/48412081/d2873ede-1032-4810-8403-dbc35d8619bd)

**Comment by amtoaer** [comment]
有确认过视频编码吗？按照程序默认编码优先级应该会使用av1，如果浏览器下载的编码是 avc 可能会有这种差距。（因为 av1 和 hevc 这两个是更现代的视频编码，同质量视频占用的空间会比 avc 小）

**Comment by shuer001** [comment]
确实是视频编码不同，如下图：
![QQ截图20240414132746](https://github.com/amtoaer/bili-sync/assets/48412081/b4ba5a83-2a98-47dc-b5a9-b4b9e2d30dd7)

 网上搜了一下，B站 AVC编码视频的码率会更高些？   https://www.bilibili.com/read/cv28110422/

**Comment by amtoaer** [comment]
理论上同等编码对比码率才有价值，本身新编码的作用就是实现同等画质更低码率的传输。正如文中所说：“比较公认的看法是：低码率下，HEVC比AVC能最多节省40%左右的码率时做到同等画质，AV1能再节省10%左右。”
文中指出的主要问题是 b 站的 HEVC 与 AV1 压太狠以至于实际的画面质量低于 AVC 了，不过因为我个人看不出太大差异，所以优先用的体积更小的 AV1/HEVC 编码。如果你更倾向于选择 AVC，只需要调整配置文件中 codecs 项的顺序即可，越靠前的编码越优先选择。

**Comment by shuer001** [comment]
好的，明白了 。感谢大佬耐心回答 ！
