### ISSUE TITLE
方便写一个在Windows docker部署的教程吗

### ISSUE THREAD

**Issue by gakaks** [amtoaer/bili-sync#61]
没有nas 想在Windows上尝试一下 没搞明白 求一个在Windows docker部署的教程（给大佬递茶）

**Comment by amtoaer** [comment]
Windows 的 docker 实际上是起了一个 Linux 虚拟机，在虚拟机里跑 Linux docker，所以直接拉 Linux 的镜像，按 Linux 的方式部署就好。请参考 [Docker Compose 示例](https://github.com/amtoaer/bili-sync?tab=readme-ov-file#docker-compose-%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B)，只需要挂载几个目录，没有其它需要配置的。

**Comment by gakaks** [comment]
![4 14-1](https://github.com/amtoaer/bili-sync/assets/43461224/5f7945f8-82f0-440f-9b34-ebc454398705)
![4 14-2](https://github.com/amtoaer/bili-sync/assets/43461224/fd0149ef-a1a1-42d4-bcd4-e12843799972)
小白不太理解 能麻烦帮忙看下我这样配置的问题出在哪里

**Comment by amtoaer** [comment]
新版 bili-sync 的配置没有分 config 和 data 两个文件夹，简单一点直接 `D:\anime\bili-sync:/app/.config/bili-sync` 就好。至于视频路径和 `metadata\people` 的挂载和你具体想要存储的路径有关，具体请参考文档。
你需要理解的是，bili-sync-rs 程序运行在容器内部，只能访问到你挂载的目标路径（在你的例子里，是 /app/thumb 和 /Videos/Bilibilis）。所以在 config.toml 里写 D、H 是错误的，肯定访问不到。这是 docker 本身的设计，不是 Windows Docker 的问题。
