### ISSUE TITLE
windows版本启动后config配置文件被覆盖

### ISSUE THREAD

**Issue by hcl910419** [amtoaer/bili-sync#62]
windows版本启动后闪退, 并且config.toml配置文件被覆盖,覆盖后的config如图
![捕获](https://github.com/amtoaer/bili-sync/assets/82689589/9ea9495c-1e49-4975-9e75-fe48b7b09d74)

**Comment by amtoaer** [comment]
没理解，你的意思是之前自己已经写过配置文件了，但是在运行时被一个空配置覆盖掉了？

**Comment by hcl910419** [comment]
> 没理解，你的意思是之前自己已经写过配置文件了，但是在运行时被一个空配置覆盖掉了？

对，试过多次，每次运行就被覆盖，系统是win10

**Comment by Moyuuko** [comment]
> > 没明白，你的意思是在自己已经写过配置文件了，在运行时被一个空配置覆盖掉了？
> 
> 对，试运行多次，每次运行就被覆盖，系统是win10

遇到过这种情况，是你配置文件格式错了

**Comment by Moyuuko** [comment]
也许是你路径单引号的问题

**Comment by amtoaer** [comment]
那感觉有必要修一下，应该是文件不存在时再覆盖写入，文件已经存在但读取发生错误时直接提示错误。
不过目前来看应该就是配置文件内容错误， 你可以检查一下你的配置和初始配置有什么差异，或者你直接贴一下自己修改后的样例配置，我看看能不能检查出问题

**Comment by hcl910419** [comment]
> 也许是你路径单引号的问题

![Screenshot_20240418_125000](https://github.com/amtoaer/bili-sync/assets/82689589/f71e93d1-c933-45b3-b670-51ac0d20bb81)
这个是实际配置的文件

**Comment by gakaks** [comment]
> > 也许是你路径单引的问题
> 
> ![截图_20240418_125000](https://private-user-images.githubusercontent.com/82689589/323469022-f71e93d1-c933-45b3-b670-51ac0d20bb81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDEwMzUsIm5iZiI6MTcxMzQ0MDczNSwicGF0aCI6Ii84MjY4OTU4OS8zMjM0NjkwMjItZjcxZTkzZDEtYzkzMy00NWIzLWI2NzAtNTFhYzBkMjBiYjgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZmY5MjIzMDdlNGQ3ZThjM2I5NjU0MDRjZGUwZjBhMmYxZTg2YWE2M2VlYjBjYTFiZWIzMjZkZGJmYzc4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.65-sj8gWhct6lir9VTbrBQPWyRLy-VMt674q81F4sE4) 这是实际配置的文件

这题我会 路径不要写本地的 写你容器挂载的对应路径就好了

**Comment by hcl910419** [comment]
> > > 也许是你路径单引的问题
> > 
> > 
> > ![截图_20240418_125000](https://private-user-images.githubusercontent.com/82689589/323469022-f71e93d1-c933-45b3-b670-51ac0d20bb81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDEwMzUsIm5iZiI6MTcxMzQ0MDczNSwicGF0aCI6Ii84MjY4OTU4OS8zMjM0NjkwMjItZjcxZTkzZDEtYzkzMy00NWIzLWI2NzAtNTFhYzBkMjBiYjgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZmY5MjIzMDdlNGQ3ZThjM2I5NjU0MDRjZGUwZjBhMmYxZTg2YWE2M2VlYjBjYTFiZWIzMjZkZGJmYzc4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.65-sj8gWhct6lir9VTbrBQPWyRLy-VMt674q81F4sE4) 这是实际配置的文件
> 
> 这题我会 路径不要写本地的 写你容器挂载的对应路径就好了

这个不是docker版本, 是win的版本哎

**Comment by gakaks** [comment]
> > > > 也许是你路径单引的问题
> > > 
> > > 
> > > ![截图_20240418_125000](https://private-user-images.githubusercontent.com/82689589/323469022-f71e93d1-c933-45b3-b670-51ac0d20bb81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDEwMzUsIm5iZiI6MTcxMzQ0MDczNSwicGF0aCI6Ii84MjY4OTU4OS8zMjM0NjkwMjItZjcxZTkzZDEtYzkzMy00NWIzLWI2NzAtNTFhYzBkMjBiYjgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZmY5MjIzMDdlNGQ3ZThjM2I5NjU0MDRjZGUwZjBhMmYxZTg2YWE2M2VlYjBjYTFiZWIzMjZkZGJmYzc4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.65-sj8gWhct6lir9VTbrBQPWyRLy-VMt674q81F4sE4) 这是实际配置的文件
> > 
> > 
> > 这题我会 路径不要写本地的 写你容器挂载的对应路径就好了
> 
> 这个不是docker版本, 是win的版本哎

![4 14-5](https://github.com/amtoaer/bili-sync/assets/43461224/47546b29-f606-4bfc-930d-2ead74d624b3)
我已经问过了 何不一试
