### ISSUE TITLE
docker无法定时扫描

### ISSUE THREAD

**Issue by oasisgallagher97** [amtoaer/bili-sync#65]
配置文件里的interval似乎没有作用，只能重启容器后才会下载新收藏的内容。

还有一个问题，我在配置文件中配了两个收藏夹，但是似乎每次运行docker时只会交替处理其中一个收藏夹的内容，例如第一次启动日志显示处理A收藏夹的内容，下一次启动则显示处理B文件夹的内容。

另外下载合集的时候，有的分P会显示error decoding response body错误导致无法下载。

**Comment by amtoaer** [comment]
error decoding response body 我没有遇到过，感觉可能是网络波动问题。程序内有重试机制，后续会继续尝试多次，这个错误应该不会有很大的影响。
至于你说的交替处理，现在程序在收藏夹级别是串行处理的，理论上总会按照你填写的顺序运行才对。程序会处理完一个收藏夹后才会处理下一个，可以观察日志里有没有出现：
```
下载收藏夹: xxx - xxx 中未处理过的视频完成
```
的提示，有这个提示才说明某个收藏夹处理完成，否则日志卡住而没有处理下一个收藏夹，可能只是因为上个收藏夹里有一个很大的视频正在下载。

**Comment by oasisgallagher97** [comment]
好的，还有就是现在换架构之后日志不会再更新了，不知道是什么原因，比如我刚刚看日志就停留在4月18日，即使我收藏新视频，数据库文件也不会再写入

**Comment by amtoaer** [comment]
可以试试[2.0.1](https://github.com/amtoaer/bili-sync/releases/tag/v2.0.1)
