### ISSUE TITLE
从1.0迁移的指引？

### ISSUE THREAD

**Issue by lemonhall** [amtoaer/bili-sync#66]
我最近正在学rust

up主能否给一个从1.0迁移的指引？我视频数实在太多，折腾不起，需要平滑迁移

比如：

1、数据库的迁移指引，我自己写个脚本，把1.0的数据库迁移到2.0都可以

**Comment by amtoaer** [comment]
暂时没有很好的解决方法，目前想到的方案是加上一个 --scan-only 之类的参数，加上这个参数后仅写入数据库记录，不触发实际下载。
等一次扫描结束后，停止程序，手动打开旧数据库查看已下载视频中最大的 favtime，然后将新数据库中所有 favtime 小于等于那个值的视频标记为失效，这样程序后续运行就会认为这些已经下载过的视频是失效的，从而避免下载。
但不管怎样这个迁移都不算平滑，如果你觉得这样可以接受，那我后面抽空实现一下这个参数。

**Comment by lemonhall** [comment]
可以的可以的，我是所有视频都放在一个收藏夹里，所以量很大

那我等一下，十分感谢。。。。

**Comment by amtoaer** [comment]
麻烦尝试一下 [2.0.1](https://github.com/amtoaer/bili-sync/releases/tag/v2.0.1) 的 scan-only 参数是否能解决问题，有问题的话再重新打开。
