### ISSUE TITLE
Credential频繁刷新问题

### ISSUE THREAD

**Issue by FakeXKng** [amtoaer/bili-sync#67]
在实际使用中发现在浏览器登录b站会频繁刷新 Credential，导致总需要手动配置非常繁琐。
请问目前是否有解决方法？
或者是否考虑加入使用账号密码登录b站自动获取Credential的功能？

**Comment by amtoaer** [comment]
程序模仿了[上游 api 文档](https://socialsisteryi.github.io/bilibili-API-collect/docs/login/cookie_refresh.html)中描述的行为，会在每日第一次请求时进行 credential 检测，并在需要刷新时自动刷新。
你提到的应该是因为将浏览器中日常使用的 credential 直接填写到了 bili-sync 中，导致两个地方同时使用同一份 credential，其中一方刷新导致另一方失效的问题。解决方法也很简单：
因为每次登录的 credential 都是不同的，可以单独开一个浏览器无痕窗口，登录账号后把 credential 复制出来贴到 bili-sync 里，这样 bili-sync 单独使用一份 credential，就不会有冲突了。

**Comment by FakeXKng** [comment]
原来如此，非常感谢
