### ISSUE TITLE
下载完成后视频的文件名是无后缀的tmp_BV1xxxx_video，不过视频能顺利播放

### ISSUE THREAD

**Issue by shareavave** [amtoaer/bili-sync#69]
运行并下载都很顺利，但是下载的结果为↓

![image](https://github.com/amtoaer/bili-sync/assets/58329716/92185cbf-94cc-4a30-b07f-dcadb9b7bb81)

环境为群晖的Container Manager，仔细看了命名操作方法，但docker水平处于凑合会用的状态所以不会加参数  = =

我的config文件是这样写的 ↓
![image](https://github.com/amtoaer/bili-sync/assets/58329716/5a948a3d-ad9a-45c8-8e8c-cb5458e57765)

有时间还请回复一下感谢先。

顺便，能支持自动将每个视频的内容封装为一个BV号文件夹便是更好...

**Comment by amtoaer** [comment]
你使用的是 1.x 版本吗？目前主要在更新的是 2.x 版本，1.x 版本问题的处理优先级比较低。
此外，1.x 版本理应默认会对每个视频创建 BV 号文件夹，并将 tmp 视频合并的，你有在日志中看到任何错误吗？或者是在程序下载视频的中途将程序中断了？

**Comment by shareavave** [comment]
> 你使用的是 1.x 版本吗？目前主要在更新的是 2.x 版本，1.x 版本问题的处理优先级比较低。 此外，1.x 版本理应默认会对每个视频创建 BV 号文件夹，并将 tmp 视频合并的，你有在日志中看到任何错误吗？或者是在程序下载视频的中途将程序中断了？

原来如此。我在下载的时候没有注意版本docker的版本TAG，所以用的是amtoaer/bili-sync的1.x，我好像应该下载amtoaer/bili-sync-rs 。
谢谢，我安装amtoaer/bili-sync-rs试一下。

————
日志中没有错误，现在想来可能是我配置的时候重启终止了导致的。

感谢。

**Comment by shareavave** [comment]
> 你使用的是 1.x 版本吗？目前主要在更新的是 2.x 版本，1.x 版本问题的处理优先级比较低。 此外，1.x 版本理应默认会对每个视频创建 BV 号文件夹，并将 tmp 视频合并的，你有在日志中看到任何错误吗？或者是在程序下载视频的中途将程序中断了？

更新，十分顺利！感谢。

————
