### ISSUE TITLE
是否能在配置中添加“是否下载完整分p视频”

### ISSUE THREAD

**Issue by kkkdkk** [amtoaer/bili-sync#72]
有时候只需要下载收藏夹中的那个视频就好，而不需要下载完整的全集视频。现在没有配置可以选择，有时候会下载几百个不需要的视频。能否添加一个配置，由用户自主决定是否下载单集

**Comment by amtoaer** [comment]
这个没办法做到。收藏夹是针对视频而非视频分页的，所以即使你只想收藏多页视频的某一页，实际上也只能记录到你对这个视频的收藏，不能定位到你具体收藏的分页。
在 1.x 版本的实现中，如果关闭分页视频下载，实际行为是下载分页视频的第一页，而第一页很可能并不是你收藏的那一页，不符合用户的实际预期，所以在 2.x 版本中移除了这个选项。
从 b 站的设计也可以看出，所谓分页视频其实是一个完整视频的多个片段，理应被认作一个整体。这种一个视频有几百个不相关的独立分页的情况，实际上是 up 主滥用了视频分页投稿，他应该采用的正确投稿方式是”视频合集”。

**Comment by kkkdkk** [comment]
> 这个没办法做到。收藏夹是针对视频而非视频分页的，所以即使你只想收藏多页视频的某一页，实际上也只能记录到你对这个视频的收藏，不能定位到你具体收藏的分页。
> 在 1.x 版本的实现中，如果关闭分页视频下载，实际行为是下载分页视频的第一页，而第一页很可能并不是你收藏的那一页，不符合用户的实际预期，所以在 2.x 版本中移除了这个选项。
> 从 b 站的设计也可以看出，所谓分页视频其实是一个完整视频的多个片段，理应被认作一个整体。这种一个视频有几百个不相关的独立分页的情况，实际上是 up 主滥用了视频分页投稿，他应该采用的正确投稿方式是”视频合集”。

好的，感谢回复。之前不理解移除这个功能的原因，现在了解了😁
