### ISSUE TITLE
是否可以支持某个up主的合集，这样就可以自动下载录播等视频了

### ISSUE THREAD

**Issue by buyfakett** [amtoaer/bili-sync#79]
我找了一下接口，理论上应该可以实现
![image](https://github.com/amtoaer/bili-sync/assets/46560426/63292735-0811-494c-9b77-df4ce8adec9a)

**Comment by amtoaer** [comment]
是的，理论上可以实现，有相关的[接口文档](https://socialsisteryi.github.io/bilibili-API-collect/docs/video/collection.html)。
主要是添加这个功能要做的变更比较大，然后我个人没什么需求，所以有点提不起干劲做（x
等把 bug 修差不多了可以抽空做一下。

**Comment by buyfakett** [comment]
好的：）
我个人主要写py，但是现在重构成rust了，不能贡献了：（

**Comment by jianzhichu** [comment]
期待这个功能加上，那种教学视频都是合集的。这个不支持，就只能用其他工具下载了

**Comment by shuer001** [comment]
这个功能挺好，有些博主的视频或者教学视频都下载是挺方便的，

**Comment by Sineater-ass** [comment]
![111](https://github.com/amtoaer/bili-sync/assets/78713624/24f7d760-acec-4e00-bd8b-07aecaaebd6e)
暂时配合bili助手使用的，但极其不好用，每下完一个合集就要重新改路径，不过总比没有好

**Comment by Sineater-ass** [comment]
> ![111](https://private-user-images.githubusercontent.com/78713624/328840385-24f7d760-acec-4e00-bd8b-07aecaaebd6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE4ODksIm5iZiI6MTcxNTE2MTU4OSwicGF0aCI6Ii83ODcxMzYyNC8zMjg4NDAzODUtMjRmN2Q3NjAtYWNlYy00ZTAwLWJkOGItMDdhZWNhYWViZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MDhhZWEzZGUwZTk0MzllNzM1ZmNlZjgyNTA3ZTQ0NDJlNTE4N2M1ZTlhZWMzNWY2OTI2ZjVjYTZiN2MzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BU_ENnnHhKW4LrsaqFmLlu2WzuHqBBV57vihd2Km_8) 暂时配合bili助手使用的，但极其不好用，每下完一个合集就要重新改路径，不过总比没有好

这个ACGhelper可以添加某个up主到自建收藏夹，然后在用bili-sync同步到NAS里

**Comment by 15823382203** [comment]
> 是的，理论上可以实现，有相关的[接口文档](https://socialsisteryi.github.io/bilibili-API-collect/docs/video/collection.html)。 主要是添加这个功能要做的变更比较大，然后我个人没什么需求，所以有点提不起干劲做（x 等把 bug 修差不多了可以抽空做一下。

大佬支持下合集下载呀。现在只有那种分了p1 p2 p3.....的这种合集才能下载时全部下载。但好多合集都不支持需要一个一个视频保存到收藏里才能一起下载，上百个视频那种合集一个一个保存太难了

**Comment by amtoaer** [comment]
最新版本已支持合集下载，不过需要手动添加。接下来会支持 UP 投稿视频的下载。
至于直接选择某个 up 主的合集，可能要等目前的 todo 搞完，后面尝试写前端的时候加上 up 主搜索之类的功能。
