### ISSUE TITLE
建议视频增加一张背景图方便emby展示

### ISSUE THREAD

**Issue by gakaks** [amtoaer/bili-sync#83]
emby启用了使用背景图功能 有无背景图效果差很远 目前只有封面图 加一张命名为fanart的背景图（哪怕同样是封面图）效果会更好 
![1](https://github.com/amtoaer/bili-sync/assets/43461224/ae8d9f73-fc97-4161-a1e0-d3e25a8e833c)
![2](https://github.com/amtoaer/bili-sync/assets/43461224/db69f8cb-0228-438c-b82d-0dc7d689519e)

**Comment by amtoaer** [comment]
get，有空了做一下

**Comment by amtoaer** [comment]
https://github.com/amtoaer/bili-sync/releases/tag/v2.0.3
