### ISSUE TITLE
每次开始下载收藏夹里面文件的时候，会有：Failed to acquire connection from pool: Connection pool  timed out

### ISSUE THREAD

**Issue by wesmile8** [amtoaer/bili-sync#86]
启动docker加载配置文件后开始下载视频，但是收藏夹里面的视频还没有下载完成的时候就会出现Failed to acquire connection from pool: Connection pool  timed out，然后会跳过这个收藏夹，开始处理另一个收藏夹
![image](https://github.com/amtoaer/bili-sync/assets/75376418/4ba8c3c0-b93a-4ac5-aa40-58d97ff32ba1)

**Comment by amtoaer** [comment]
看起来是 sqlite 的问题，不过这个应该影响不大，所有未下载成功的视频都会在下次轮询时触发重新下载。
我尝试放宽一下数据库连接池选项，看看能不能解决一下吧。
