### ISSUE TITLE
请问可以指定收藏夹吗

### ISSUE THREAD

**Issue by fhkfds** [amtoaer/bili-sync#9]
收藏夹里很多都是为了一键三连收藏的没有什么营养的视频

**Comment by amtoaer** [comment]
可以，path mapper 是一个字典，需要同步的收藏夹需要写在这个字典里，默认为空。
对于每个需要同步的收藏夹，key 是你要同步的收藏夹 id（网页版 b 站打开这个收藏夹在 url 里应该能看到），value 是这个收藏夹里的视频存储到的位置。
