### ISSUE TITLE
启动后不工作

### ISSUE THREAD

**Issue by 2282230595** [amtoaer/bili-sync#92]
应该是哪里设置问题，启动后不会正常运行，重新下载镜像重新创建容器也都试过，
![screencapture-xia9999-synology-me-5001-2024-05-01-22_16_12](https://github.com/amtoaer/bili-sync/assets/32991814/69d21eaf-8b41-43e9-bf31-79b213001103)
![screencapture-xia9999-synology-me-5001-2024-05-01-22_17_07](https://github.com/amtoaer/bili-sync/assets/32991814/8ce5f6b7-dc40-4310-8097-7b90b46e34de)
![screencapture-xia9999-synology-me-5001-2024-05-01-22_22_26](https://github.com/amtoaer/bili-sync/assets/32991814/98869238-2974-4707-9ecd-233934442dbc)

[amtoaer-bili-sync-rs-1.csv](https://github.com/amtoaer/bili-sync/files/15177982/amtoaer-bili-sync-rs-1.csv)

**Comment by amtoaer** [comment]
日志不是显示已经在正常运行了吗，你说的不工作是指什么？

**Comment by 2282230595** [comment]
就像卡住了一样，不会下载新的视频，重新启动也是接着上次的位置一动不动

**Comment by 2282230595** [comment]
实在不好意思，我也不太懂怎么表达这个问题![2df0f9eafbbedf04b077587054c00ca](https://github.com/amtoaer/bili-sync/assets/32991814/92027c50-46ea-455b-918c-e956802f082a)
![8666ef5779e8f3fe403956fa5a323be](https://github.com/amtoaer/bili-sync/assets/32991814/74798695-0369-4a72-a34b-0c623ac4d965)

**Comment by 2282230595** [comment]
> 日志不是显示已经在正常运行了吗，你说的不工作是指什么？
麻烦了，

**Comment by amtoaer** [comment]
你这个收藏夹里是不是有什么非常大的视频，一直在等这个视频下载完成？
建议找一下收藏夹目录下的 tmp 文件，看看具体是哪个，然后看看这个文件大小是不是一直在增长。
比如在收藏夹的保存目录执行一下：`find . -name '*tmp*'`

**Comment by 2282230595** [comment]
> 日志不是显示已经正常运行了吗，你说的不工作是指什么？

🥺

**Comment by 2282230595** [comment]
> 你这个收藏夹里是不是有什么非常大的视频，一直在等这个视频下载完成？ 建议找一下收藏夹目录下的 tmp 文件，看看具体是哪个，然后看看这个文件大小是不是一直在增长。 比如在收藏夹的保存目录执行一下：`find . -name '*tmp*'`

没有大的视频，容器也没有一点流量波动
![37cbd34bfc28ed993001a55ba47b663](https://github.com/amtoaer/bili-sync/assets/32991814/f2873e69-9abb-4a17-9625-f4f15de47340)
![screencapture-xia9999-synology-me-5001-2024-05-01-23_08_38](https://github.com/amtoaer/bili-sync/assets/32991814/99620ac1-a95f-412f-b1ea-652bec959a6f)

**Comment by 2282230595** [comment]
看文件夹里也是合并过了
![1714576742438](https://github.com/amtoaer/bili-sync/assets/32991814/177cb52a-0a64-4cd7-9875-e761f16b3869)

**Comment by amtoaer** [comment]
现在视频是十个一组保存下载状态的，如果还没凑够十个就被强制终止，是会出现这个情况，这是正常现象。
程序的下载逻辑是下载 tmp_video 和 tmp_audio，然后将其合并为 mp4，同时删除掉两个 tmp 文件，你需要看的是**程序卡住时存在 tmp 的视频**，这说明程序卡在了那个视频的下载，应该是那个视频导致的问题。

**Comment by amtoaer** [comment]
分p视频程序会下载全部分p（程序确保单个视频最多五个分p同时下载），以及现在已经启用了 read timeout，如果三十秒没有收到任何数据会报 timeout 错误。所以这种情况我只能理解成下载速度很慢（但没有中断）导致的假死现象..

**Comment by amtoaer** [comment]
我尝试调整下并发下载的数量并减少 read timeout，看看会不会有缓解。

**Comment by amtoaer** [comment]
可以麻烦试试 https://github.com/amtoaer/bili-sync/releases/tag/v2.0.5 吗？这个版本降低了并发下载量和 read timeout，不清楚能否缓解这个问题。

**Comment by 2282230595** [comment]
> 可以麻烦试试 https://github.com/amtoaer/bili-sync/releases/tag/v2.0.5 吗？这个版本降低了并发下载量和 read timeout，不清楚能否缓解这个问题。

好的我试试看😉

**Comment by 2282230595** [comment]
> 可以麻烦试试 https://github.com/amtoaer/bili-sync/releases/tag/v2.0.5 吗？这个版本降低了并发下载量和 read timeout，不清楚能否缓解这个问题。

2.0.5没有出现这个问题了👍👍👍

**Comment by amtoaer** [comment]
嗯嗯，那看起来是因为之前允许的并发数太多导致的问题，现在最多同时下载3×2＝6个分页，之前最多同时下载5×5＝25个。
可能下载数量太多会导致单个视频迟迟下载不完，或者b站那边有做这方面的限制。我收藏的多p视频比较少所以没遇到过（
